# Generated by Django 4.2.5 on 2023-12-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_proyectodestacado_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proyecto",
            name="areaConstruida",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="areaConstruidaUrbanismo",
        ),
        migrations.AddField(
            model_name="proyecto",
            name="cancha_squash",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="cuarto_util",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="gimnasio",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="lobby",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="parque_infantil",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="parque_mascotas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="parqueaderos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="piscina",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="sala_cine",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="salon_social",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="senderos",
            field=models.BooleanField(default=False),
        ),
    ]
