# Generated by Django 4.2.5 on 2023-12-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_remove_proyecto_areaconstruida_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proyecto",
            old_name="is_vis",
            new_name="vis",
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Entregado", "Entregado"),
                    ("En construcción", "En construcción"),
                    ("Lanzamiento", "Lanzamiento"),
                    ("En ventas", "En ventas"),
                ],
                max_length=50,
            ),
        ),
    ]
