# Generated by Django 4.2.5 on 2023-12-20 23:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_proyecto_comercial"),
        ("main", "0011_rename_is_vis_proyecto_vis_alter_proyecto_estado"),
    ]

    operations = []
