# Generated by Django 4.2.5 on 2023-12-20 23:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_merge_20231220_1822"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proyecto",
            old_name="cancha_squash",
            new_name="luxury_home",
        ),
        migrations.RenameField(
            model_name="proyecto",
            old_name="cuarto_util",
            new_name="vivienda_turistica",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="gimnasio",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="lobby",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="parque_infantil",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="parque_mascotas",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="parqueaderos",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="piscina",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="sala_cine",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="salon_social",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="senderos",
        ),
    ]
