# Generated by Django 4.2.5 on 2023-12-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_rename_cancha_squash_proyecto_luxury_home_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfoContacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cel", models.CharField(blank=True, max_length=12, null=True)),
                ("tel", models.CharField(blank=True, max_length=12, null=True)),
                ("correo", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="InfoUbicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direccion", models.CharField(blank=True, max_length=50, null=True)),
                ("horario", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Nosotros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seccion",
                    models.CharField(
                        choices=[("Misión", "Misión"), ("Visión", "Visión")],
                        max_length=50,
                    ),
                ),
                ("descripcion", models.TextField()),
            ],
        ),
    ]
