# Generated by Django 4.2.5 on 2023-12-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_infocontacto_infoubicacion_nosotros"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "seccion",
                    models.CharField(
                        choices=[("Contacto", "Contacto"), ("Ubicación", "Ubicación")],
                        max_length=50,
                    ),
                ),
                ("contenido", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="InfoContacto",
        ),
        migrations.DeleteModel(
            name="InfoUbicacion",
        ),
    ]
