# Generated by Django 4.2.5 on 2023-12-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_contacto_delete_infocontacto_delete_infoubicacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="prioridad",
            field=models.CharField(
                choices=[
                    ("Entregado", "Entregado"),
                    ("En construcción", "En construcción"),
                    ("Lanzamiento", "Lanzamiento"),
                    ("En ventas", "En ventas"),
                ],
                default="Baja",
                max_length=50,
            ),
        ),
    ]
